"""Gerador C a partir de TAC — MVP Fase 2 (reuso projeto_compiladores)."""

from __future__ import annotations

from typing import Dict, List, Optional

from minipar_core.translation.tac import TAC


class SimpleCCodeGenerator:
    """Gera C compilável para subset MVP: print, funções, main entry."""

    def __init__(self) -> None:
        self.functions: Dict[str, List[str]] = {}
        self.current_fn: Optional[str] = None
        self.fn_body: List[str] = []
        self.main_body: List[str] = []
        self.strings: Dict[str, str] = {}
        self.string_id = 0
        self.pending_params: List[str] = []
        self.oo_types: Dict[str, str] = {}
        self.oo_classes: set[str] = set()
        self.pending_method: tuple[str, str, str] | None = None
        self.instance_methods: set[str] = set()

    def _esc(self, s: str) -> str:
        return s.replace("\\", "\\\\").replace('"', '\\"').replace("\n", "\\n")

    def _str_label(self, raw: str) -> str:
        if raw not in self.strings:
            self.strings[raw] = f"str_{self.string_id}"
            self.string_id += 1
        return self.strings[raw]

    def _target_body(self) -> List[str]:
        if self.current_fn:
            return self.fn_body
        return self.main_body

    def _emit(self, line: str) -> None:
        self._target_body().append(line)

    def generate(self, instructions: List[TAC]) -> str:
        self.functions = {}
        self.current_fn = None
        self.fn_body = []
        self.main_body = []
        self.pending_params = []
        self.strings = {}
        self.string_id = 0
        self.oo_types = {}
        self.oo_classes = set()
        self.pending_method = None
        self.instance_methods = set()

        for instr in instructions:
            self._emit_instr(instr)

        if self.current_fn:
            self.functions[self.current_fn] = self.fn_body
            self.current_fn = None
            self.fn_body = []

        out: List[str] = [
            "/* Generated by MiniPar ms-codegen-c (Fase 2+) */",
            "#include <stdio.h>",
            "#include <stdlib.h>",
            "#include <string.h>",
            "#include <math.h>",
            "",
        ]

        for cls in sorted(self.oo_classes):
            out.append(f"typedef struct {{ int _tag; }} {cls};")
            out.append(f"void* {cls}_new(void) {{ return calloc(1, sizeof({cls})); }}")
            out.append(f"void* {cls}_get_field(void* self) {{ (void)self; return 0; }}")
            out.append("")

        if self.strings:
            out.append("/* string literals */")
            for raw, label in self.strings.items():
                inner = raw[1:-1] if raw.startswith('"') else raw
                out.append(f'const char* {label} = "{self._esc(inner)}";')
            out.append("")

        for name, body in self.functions.items():
            if name in self.instance_methods:
                out.append(f"void {name}(void* this) {{")
            else:
                out.append(f"void {name}(void) {{")
            out.extend(f"    {line}" for line in body)
            out.append("}")
            out.append("")

        out.append("int main(void) {")
        if "Main_run" in self.functions:
            out.append("    Main_run();")
        elif self.main_body:
            out.extend(f"    {line}" for line in self.main_body)
        out.append("    return 0;")
        out.append("}")
        return "\n".join(out)

    def _emit_instr(self, instr: TAC) -> None:
        op = instr.op

        if op == "FUNC_BEGIN":
            if self.current_fn:
                self.functions[self.current_fn] = self.fn_body
            self.current_fn = instr.arg1
            self.fn_body = []
            if isinstance(self.current_fn, str) and "_" in self.current_fn:
                cls, method = self.current_fn.split("_", 1)
                if cls not in ("Global", "Main") and method != "run":
                    self.instance_methods.add(self.current_fn)
                    self.oo_classes.add(cls)
            return

        if op == "FUNC_END":
            if self.current_fn:
                self.functions[self.current_fn] = self.fn_body
            self.current_fn = None
            self.fn_body = []
            return

        if op in ("CALL_MAIN",):
            return

        if op == "PRINT":
            val = instr.arg1
            newline = instr.arg2 == "1"
            if isinstance(val, str) and val.startswith('"'):
                label = self._str_label(val)
                if newline:
                    self._emit(f'printf("%s\\n", {label});')
                else:
                    self._emit(f'printf("%s", {label});')
            elif newline:
                self._emit(f'printf("%g\\n", (double)({val}));')
            else:
                self._emit(f'printf("%g", (double)({val}));')
            return

        if op == "ASSIGN":
            src = str(instr.arg1)
            dst = str(instr.result)
            if src in self.oo_types:
                self.oo_types[dst] = self.oo_types[src]
                self._emit(f"void* {dst} = (void*)({src});")
            else:
                self._emit(f"double {dst} = (double)({src});")
            return

        if op == "RETURN":
            if instr.arg1:
                self._emit(f"return; /* value {instr.arg1} ignored in void MVP */")
            else:
                self._emit("return;")
            return

        if op in ("+", "-", "*", "/", "%", "LT", "GT", "EQ", "NE", "LE", "GE"):
            a, b, r = instr.arg1, instr.arg2, instr.result
            cmap = {
                "+": "+",
                "-": "-",
                "*": "*",
                "/": "/",
                "LT": "<",
                "GT": ">",
                "EQ": "==",
                "NE": "!=",
                "LE": "<=",
                "GE": ">=",
            }
            if op == "%":
                self._emit(f"double {r} = fmod((double)({a}), (double)({b}));")
            elif op in ("LT", "GT", "EQ", "NE", "LE", "GE"):
                self._emit(
                    f"double {r} = ((double)({a}) {cmap[op]} (double)({b})) ? 1.0 : 0.0;"
                )
            else:
                self._emit(f"double {r} = (double)({a}) {cmap[op]} (double)({b});")
            return

        if op == "UNARY":
            self._emit(
                f"double {instr.result} = ({instr.arg2} (double)({instr.arg1}));"
            )
            return

        if op == "LABEL":
            self._emit(f"{instr.arg1}:")
            return

        if op == "GOTO":
            self._emit(f"goto {instr.arg1};")
            return

        if op == "IF_FALSE":
            self._emit(f"if (!((double)({instr.arg1}))) goto {instr.result};")
            return

        if op == "PARAM":
            self.pending_params.append(str(instr.arg1))
            return

        if op == "CALL":
            n_args = int(instr.arg2 or 0)
            args = ", ".join(self.pending_params[-n_args:])
            self.pending_params = self.pending_params[:-n_args]
            self._emit(f"/* call {instr.arg1}({args}) -> {instr.result} */")
            return

        if op in (
            "SEQ_BEGIN",
            "SEQ_END",
            "PAR_BEGIN",
            "PAR_END",
            "THREAD_START",
            "THREAD_END",
        ):
            return

        if op == "LIST_LEN":
            self._emit(f"double {instr.result} = 0; /* list MVP */")
            return

        if op == "LIST_GET":
            self._emit(f"double {instr.result} = 0; /* list get MVP */")
            return

        if op in ("METHOD_CALL", "NEW", "GET_PROP", "SET_PROP", "METHOD_ARGS"):
            if op == "NEW":
                cls = str(instr.arg1)
                n_args = int(instr.arg2 or 0)
                result = instr.result
                self.oo_classes.add(cls)
                self.oo_types[str(result)] = cls
                args = ", ".join(self.pending_params[-n_args:]) if n_args else ""
                self.pending_params = self.pending_params[:-n_args] if n_args else self.pending_params
                if args:
                    self._emit(f"void* {result} = {cls}_new({args});")
                else:
                    self._emit(f"void* {result} = {cls}_new();")
                return

            if op == "METHOD_CALL":
                self.pending_method = (
                    str(instr.arg1),
                    str(instr.arg2),
                    str(instr.result),
                )
                return

            if op == "METHOD_ARGS":
                if not self.pending_method:
                    return
                receiver, method, _result = self.pending_method
                self.pending_method = None
                n_args = int(instr.arg1 or 0)
                extra = self.pending_params[-n_args:] if n_args else []
                self.pending_params = self.pending_params[:-n_args] if n_args else self.pending_params
                cls = self.oo_types.get(receiver, "Object")
                fn = f"{cls}_{method}"
                call_args = [receiver] + extra
                self._emit(f"{fn}({', '.join(call_args)});")
                return

            if op == "GET_PROP":
                receiver = str(instr.arg1)
                prop = str(instr.arg2)
                result = instr.result
                cls = self.oo_types.get(receiver, "Object")
                self._emit(f"void* {result} = {cls}_get_{prop}({receiver});")
                return

            if op == "SET_PROP":
                receiver = str(instr.arg1)
                prop = str(instr.arg2)
                value = str(instr.arg3)
                cls = self.oo_types.get(receiver, "Object")
                self._emit(f"{cls}_set_{prop}({receiver}, {value});")
                return

        self._emit(f"/* unhandled TAC: {instr} */")
