"""Back-end Rust — emissão mínima + rustc opcional."""

from __future__ import annotations

import subprocess
import tempfile
import uuid
from pathlib import Path

from minipar_core.translation.base_translator import (
    AbstractBackendTranslator,
    TranslationResult,
)
from minipar_core.translation.ast_from_json import from_dict
from minipar_core import ast_nodes as n


class RustBackend(AbstractBackendTranslator):
    def __init__(self) -> None:
        self._code = ""
        self._output = ""

    def emit(self, ast_dict: dict) -> None:
        self._code = self._emit_rust(from_dict(ast_dict))

    def finalize(self) -> TranslationResult:
        result = self._try_build(self._code)
        return TranslationResult(
            output=result["output"],
            code=self._code,
            exit_code=result["exit_code"],
        )

    def _emit_rust(self, program: n.Program) -> str:
        prints: list[str] = []
        self._collect_prints(program, prints)
        body = "\n".join(f'    println!("{self._esc(p)}");' for p in prints)
        if not body:
            body = '    println!("MiniPar Rust MVP");'
        return f"""// Generated by MiniPar ms-codegen-rust (Fase 2)
fn main() {{
{body}
}}
"""

    def _collect_prints(self, node, out: list[str]) -> None:
        if node is None:
            return
        if isinstance(node, n.Program):
            for d in node.declarations:
                self._collect_prints(d, out)
        elif isinstance(node, n.ClassDecl):
            for m in node.members:
                self._collect_prints(m, out)
        elif isinstance(node, n.MethodDecl):
            self._collect_prints(node.body, out)
        elif isinstance(node, n.Block):
            for s in node.statements:
                self._collect_prints(s, out)
        elif isinstance(node, n.PrintStmt) and node.newline:
            for arg in node.arguments:
                if isinstance(arg, n.StringLiteral):
                    out.append(arg.value)

    @staticmethod
    def _esc(s: str) -> str:
        return s.replace("\\", "\\\\").replace('"', '\\"')

    def _try_build(self, code: str) -> dict:
        if not self._has_rustc():
            return {
                "output": "Rust code generated. rustc não encontrado — instale Rust toolchain para compilar.",
                "exit_code": 0,
            }
        work = Path(tempfile.gettempdir()) / f"minipar-rust-{uuid.uuid4().hex[:8]}"
        work.mkdir(parents=True, exist_ok=True)
        rs_file = work / "main.rs"
        exe = work / "main"
        try:
            rs_file.write_text(code, encoding="utf-8")
            comp = subprocess.run(
                ["rustc", str(rs_file), "-O", "-o", str(exe)],
                capture_output=True,
                text=True,
                check=False,
            )
            if comp.returncode != 0:
                return {
                    "output": f"rustc failed:\n{comp.stderr or comp.stdout}",
                    "exit_code": comp.returncode,
                }
            run = subprocess.run(
                [str(exe)], capture_output=True, text=True, check=False, timeout=30
            )
            stdout = run.stdout or ""
            stderr = run.stderr or ""
            log = "Compiled with rustc -O\n"
            if stdout:
                log += stdout
            if stderr:
                log += stderr
            return {"output": log, "exit_code": run.returncode}
        finally:
            for p in (rs_file, exe):
                try:
                    p.unlink(missing_ok=True)
                except OSError:
                    pass
            try:
                work.rmdir()
            except OSError:
                pass

    @staticmethod
    def _has_rustc() -> bool:
        try:
            proc = subprocess.run(
                ["rustc", "--version"],
                capture_output=True,
                check=False,
            )
            return proc.returncode == 0
        except FileNotFoundError:
            return False


def generate_rust(ast_dict: dict) -> TranslationResult:
    return RustBackend().translate(ast_dict)
